# ========================
# REDIS
# ========================
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}

# ========================
# DATABASE
# ========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================
# JPA
# ========================
spring.sql.init.mode=${SQL_INIT_MODE:never}
spring.sql.init.data-locations=classpath:sampleData.sql,classpath:db/seed/vietnam_provinces_2025.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=false

# ========================
# MAIL
# ========================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ========================
# PAYOS
# ========================
payos.return-url=${PAYOS_RETURN_URL:http://localhost:5173/payment/return}
payos.cancel-url=${PAYOS_CANCEL_URL:http://localhost:5173/payment/cancel}

# ========================
# LOGGING
# ========================
logging.level.root=INFO
logging.level.org.springframework.security=INFO
