# ========================
# DATABASE
# ========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ========================
# JWT (SECURE)
# ========================
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# ========================
# ENCRYPTION
# ========================
encryption.secret-key=${ENCRYPTION_SECRET_KEY}
api.key=${API_KEY}
# ========================
# SECURITY HARDENING
# ========================
server.error.include-message=never
server.error.include-stacktrace=never

# ========================
# LOGGING
# ========================
logging.level.root=WARN
logging.level.org.springframework.security=ERROR


nhanh.client-id=${NHANH_CLIENT_ID}
nhanh.client-secret=${NHANH_CLIENT_SECRET}
nhanh.redirect-uri=${NHANH_REDIRECT_URI}
nhanh.base-url=https://pos.open.nhanh.vn/api