# ========================
# REDIS
# ========================
spring.data.redis.host=${REDIS_HOST:redis}

# ========================
# DATABASE
# ========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================
# JPA
# ========================
spring.sql.init.mode=${SQL_INIT_MODE:never}
spring.sql.init.data-locations=classpath:sampleData.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=true

# ========================
# NHANH
# ========================
nhanh.client-id=${NHANH_CLIENT_ID:docker-nhanh-client-id}
nhanh.business-id=${NHANH_BUSINESS_ID:docker-business-id}
nhanh.client-secret=${NHANH_CLIENT_SECRET:docker-nhanh-client-secret}
nhanh.redirect-uri=${NHANH_REDIRECT_URI:http://localhost:8081/api/nhanh/oauth/callback}

# ========================
# PAYOS
# ========================
payos.return-url=${PAYOS_RETURN_URL:http://localhost:5173/payment/return}
payos.cancel-url=${PAYOS_CANCEL_URL:http://localhost:5173/payment/cancel}

# ========================
# LOGGING
# ========================
logging.level.root=INFO
logging.level.org.springframework.security=INFO
