spring.application.name=sodu
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.codec.max-in-memory-size=10MB
server.port=8081
spring.profiles.active=dev

nhanh.client-id=${NHANH_CLIENT_ID}
nhanh.client-secret=${NHANH_CLIENT_SECRET}
nhanh.redirect-uri=${NHANH_REDIRECT_URI}
nhanh.base-url=https://pos.open.nhanh.vn/api
nhanh.api.products-url=https://pos.open.nhanh.vn/v3.0/product/list
nhanh.sync.cron=0 0 * * * *